# Generated by Django 3.0.3 on 2020-02-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200205_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_next',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_next',
            new_name='question_text',
        ),
    ]
